import React from "react";
import aboutone from "../images/about-1.jpg";
import aboutthree from "../images/about-3.jpg";
import aboutfive from "../images/about-5.jpg";
import "../Styles/About.css";

function About() {
  return (
    <div className="bg-white">
      <div className="bg-black text-center text-white  ">
        <h1 className="text-3xl">About Us</h1>
      </div>
      <div className=" topimgbg w-[100%] h-[300px] grid place-items-center text-white">
        <h1 className="text-7xl font-bold "> Who We Are</h1>
      </div>
      <div className="md:flex py-5 border-2 border-b-black">
        <div className="md:w-[40%] grid place-items-center">
          <img
            src={aboutone}
            alt="about1"
            className="md:w-[70%] w-[80%] h-[400px] border-2 border-black"
          />
        </div>
        <div className="md:w-[60%]  ">
          <h1 className="text-3xl">About</h1>
          <p className="md:text-xl">
            {" "}
            VAHAN is India’s coolest mobility platform and one of the world’s
            largest ride-hailing companies, 250+ cities across India, Australia,
            New Zealand, and the UK. The VAHAN website offers mobility solutions
            by connecting customers to drivers and a wide range of vehicles
            across bikes, auto-rickshaws, metered taxis, and cabs, enabling
            convenience and transparency for hundreds of millions of consumers
            and over 1.5 million driver-partners. VAHAN's core mobility offering
            in India is supplemented by its electric-vehicle arm,VAHAN Electric;
            India’s largest fleet management business,VAHAN Fleet Technologies
            and VAHAN Skilling, that aims to enable millions of livelihood
            opportunities for India's youth. With its acquisition of Ridlr,
            India’s leading public transportation website and investment in
            Vogo, a dockless scooter sharing solution, VAHAN is looking to build
            mobility for the next billion Indians. VAHAN also extends its
            consumer offerings like micro-insurance and credit led payments
            through VAHAN Financial Services and a range of owned food brands
            through India’s largest network of kitchens under its Food business.
            VAHAN was founded in March 2023 by Abhilash Pal with a mission to
            provide a better performance and features to travel industry.
          </p>
        </div>
      </div>
      <div className="pt-6">
        <div className="toptwo h-[500px] w-[100%] grid place-items-center">
          <h1 className="text-white text-7xl font-bold">Let's Take A Ride</h1>
        </div>
      </div>

      <div className="md:flex py-6 border-2 border-b-black">
        <div className="md:w-[60%] pl-6">
          <h1 className="lg:text-4xl">Features</h1>
          <p className="lg:text-xl">
            Cab Management System helps to undertake automate streamlining of
            cabs for the routes generated by admin. The system includes driver
            management, drop point management, vehicle management and booking
            system. This application can be used for administering the internal
            office cabs.
          </p>
          <p className="lg:text-xl">
            As taxi services are available 24/7, you can enjoy a taxi ride any
            time or during transportation emergencies. Whether you are traveling
            in a new place or in emergency situations, taxi cab services will
            help you to reach your destination safely and on time.
          </p>
          <p className="lg:text-xl">
            Economic & Affordable. With regard to ease and comfort, taxi
            services are the most economic and affordable form of
            transportation.
          </p>
          <p className="lg:text-xl">
            Saves Time. Hiring a taxi service saves a great deal of time and
            energy.
          </p>
          <p className="lg:text-xl">Professional and experienced drivers.</p>
        </div>
        <div className="md:w-[40%]">
          <img src={aboutthree} alt="about4" />
        </div>
      </div>
      <div className="pt-6">
        <div className="topthree h-[400px] w-[100%] grid place-items-center ">
          <h1 className="text-white text-7xl font-bold">Reach In Time</h1>
        </div>
      </div>

      <div className="md:flex pt-6">
        <div className="md:w-[60%] pl-4">
          <h1 className="text-2xl">Drivers Skills </h1>
          <p className="md:text-xl py-1">
            To be a confident driver who is able to drive well in any road and
            weather conditions.
          </p>
          <p className="md:text-xl py-1">
            a helpful, trustworthy and patient manner.
          </p>
          <p className="md:text-xl py-1">
            some number skills, as you'll be dealing with cash a lot.
          </p>
          <p className="md:text-xl py-1">
            to be able to deal with all types of people including the occasional
            awkward or difficult customer.
          </p>
          <p className="md:text-xl py-1">Strong driving record,Navigation.</p>
          <p className="md:text-xl py-1"> Basic maintenance knowledge.</p>
          <p className="md:text-xl py-1"> Physical fitness and strength.</p>
          <p className="md:text-xl py-1">
            fficiency and time-management And Problem-solving, Detail-oriented.
          </p>
        </div>
        <div className="md:w-[40%]">
          <img src={aboutfive} alt="about5" />
        </div>
      </div>
    </div>
  );
}

export default About;
